sudo: false
language: node_js
node_js:
  - 8
before_install:
  - npm i -g npm
install:
  - npm ci
script:
  - npm run check
  - npm test
cache:
  directories:
    - '$HOME/.npm'
env:
  - DEBUG=mon* MONGODB_VERSION=stable
  - DEBUG=mon* MONGODB_VERSION=unstable
