sudo: false
language: node_js
node_js:
  - 12.4.0
before_install:
  - npm i -g npm
script:
  - npm test
cache:
  directories:
    - '$HOME/.npm'
env:
  - DEBUG=mon* MONGODB_VERSION=stable
  - DEBUG=mon* MONGODB_VERSION=unstable
